name: kdr_partnership
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  json_serializable: ^2.0.0

  flutter:
    sdk: flutter

  #FIREBASE
  google_sign_in: ^4.0.1+3
  firebase_auth: ^0.10.0+1
  firebase_messaging: ^5.0.1
  #PUB PACKAGES
  path_provider: ^0.5.0+1
  cupertino_icons: ^0.1.2
  tuple: ^1.0.2
  connectivity: ^0.4.3+1
  image_picker: ^0.6.0+2
  flushbar: ^1.5.0
  permission:
    git:
      url: https://github.com/devadrianapostol/permission
  url_launcher: ^5.0.2
  material_search: ^0.2.8
  auto_size_text: ^1.1.2 # MUST REPLACE ALL TEXT WIDGET SOON

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/texts/terms&conditions.txt
    - assets/test.png
    - assets/img/back.png
    - assets/img/logo_partnership.png
    - assets/img/partnership_logo.png
    - assets/img/login_provider_fb.png
    - assets/img/login_provider_google.png
    - assets/img/login_provider_insta.png
    - assets/img/login_provider_twitter.png
    - assets/img/work-office.png
    - assets/img/login_logo.png
    - assets/blue_texture.jpg
    - assets/bubble_texture.jpg
    - assets/

  fonts:
    - family: Copperplate
      fonts:
        - asset: assets/fonts/OPTICopperplate.otf
        - asset: assets/fonts/OPTICopperplate-Light.otf
          weight: 100
        - asset: assets/fonts/OPTICopperplate-Heavy.otf
          weight: 700

    - family: Orkney
      fonts:
        - asset: assets/fonts/Orkney-Regular.ttf
        - asset: assets/fonts/Orkney-Regular-Italic.ttf
          style: italic
        - asset: assets/fonts/Orkney-Light.ttf
          weight: 100
        - asset: assets/fonts/Orkney-Light-Italic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Orkney-Medium.ttf
          weight: 400
        - asset: assets/fonts/Orkney-Medium-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Orkney-Bold.ttf
          weight: 700
        - asset: assets/fonts/Orkney-Bold-Italic.ttf
          weight: 700
          style: italic

    - family: PeaceSans
      fonts:
        - asset: assets/PeaceSans/Peace_Sans_Webfont.ttf

    - family: Copperhead
      fonts:
        - asset: assets/fonts/Copperhead_Condensed_Demo.ttf
